enabled: true
mark:
  texture: RED_DYE
  glow: false
  name: "&9Mark"
  lore: "&e&oYou can mark your items and they do not drop when death"
  text: "&9- Item is marked"

##
# Allowed and denied items
# ------------------------------------------
# You can use a regex for matching materials, eg diamond_.*
##
allowed:
  - iron_.+
  - diamond_chestplate
  - (cross)?bow
  - .+_leggings
denied:
  - iron_h.*
  - chainmal_leggings