name: MarkItem
version: ${project.version}
description: Mark your items
authors: [OsipXD, Dereku]
api-version: '1.13'

main: ru.endlesscode.markitem.MarkItem

commands:
   markitem:
      description: MarkItem command
      usage: /<command>
      permission: markitem.command