enabled: true
mark:
  texture: RED_DYE
  name: "&9Mark"
  lore:
    - "&e&oYou can mark your items to keep it on death"
  text:
    - "&9- Item is marked"

# Recipe will be shown to player in recipe book
recipe:
  title: "Marked Item"
  description:
    - "You can mark your items to keep it on death"

##
# Allowed and denied items
# ------------------------------------------
# You can use a regex for matching materials, eg diamond_.*
##
allowed:
  - iron_.+
  - diamond_chestplate
  - (cross)?bow
  - .+_leggings
denied:
  - iron_h.*
  - chainmal_leggings
