enabled: true

# Configurations for the item to be used as a mark
mark:
  # Here you can use any item supported by Mimic
  texture: red_dye
  name: "&9Mark"
  lore:
    - "&e&oYou can mark your items to keep it on death"
  # This text will be added to marked items
  text:
    - "&9- Item is marked"

# Recipe will be shown to player in recipe book
recipe:
  # Here you can use any item supported by Mimic
  texture: red_dye
  title: "Marked Item"
  description:
    - "You can mark your items to keep it on death"

##
# Allowed and denied items for marking.
#
# You can use simple patterns for items matching.
# The simple pattern is a subset of the shell pattern matching or [glob][https://en.wikipedia.org/wiki/Glob_(programming)]
# - '*' matches any zero or more characters
# - '?' matches any one character
##
allowed:
  - '*_head'
  - '*_skull'
  - '*_helmet'
  - '*_chestplate'
  - '*_leggings'
  - '*_boots'
  - '*_sword'
  - '*_axe'
  - 'elytra'
  - 'bow'
  - 'crossbow'
  - 'trident'
  - 'shield'
denied:
  - 'wooden_*'
  - 'leather_*'
